### PR TITLE
Telegraph Plugin for Lazy People : P

### PR DESCRIPTION
**Pull request by JyothisJayanth**
Updated Telegraph Plugin,
New Commands,
.tgm as a reply to a media 
.tgt for Long Text Messages 
-----------------------------------------
By @WhySooSerious

### CODE REVIEW

**Comment by JyothisJayanth** [comment]
Oof

**Comment by leobrownlee** [comment]
Done

**Comment by StarkGang** [comment]
@JyothisJayanth Already

**Comment by JyothisJayanth** [comment]
@leobrownlee Done What?

**Comment by leobrownlee** [comment]
Update aaku img check my repo 🙃🙃

**Comment by leobrownlee** [comment]
https://github.com/leobrownlee/FRIDAY

**Comment by StarkGang** [comment]
@leobrownlee .telegraph text

**Pull request merged**
