### PR TITLE
Update pmpermit.py

### PR DESCRIPTION
**Pull request by KeshavTech246**

### CODE REVIEW

**Comment by niteshraj2310** [comment]
wew 👀

**Comment by Manish0010** [comment]
Binod

**Comment by Manish0010** [comment]
@Manish0010 Hmm

**Comment by Manish0010** [comment]
@Manish0010 Lol

**Comment by StarkGang** [comment]
@Manish0010 Lmao

**Comment by niteshraj2310** [comment]
> @Manish0010 Lmao

wassup bruh 🙂

**Comment by Manish0010** [comment]
Binod.py

**Comment by niteshraj2310** [comment]
lmao.py

**Pull request closed without merging**
